import "./style/globals.css";
import Head from "next/head";
import styles from "@/app/style/page.module.css";
import NavbarComponent from "@/app/component/navbar/navbarComponent";
import LoaderComponent from "@/app/component/loader/loaderComponent";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <>
            <LoaderComponent></LoaderComponent>

            <html lang="en">
            <Head>
                <link rel="icon" href="/project-imgs/favicon.ico" sizes="any"/>
            </Head>
            <body>
            <div className={styles.page}>
                <main className={styles.main}>
                    <NavbarComponent></NavbarComponent>

                    {children}
                </main>
            </div>
            </body>
            </html>
        </>
    );
}
