'use client'
import {useState} from 'react';
import styles from "@/app/style/add_form.module.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AddBlogPostComponent() {

    const [formTitle, setTitle] = useState('');
    const [formContent, setContent] = useState('');

    const handleSubmit = async (e) => {
        e.preventDefault();

        // Slug generate karo
        const slug = formTitle
            .toLowerCase()
            .replace(/[^a-z0-9 -]/g, '')
            .replace(/\s+/g, '-')
            .replace(/-+/g, '-');

        const newPost = {
            formTitle,
            formContent,
            slug,
            id: Date.now()
        };

        try {

            await fetch('/api/savePostBlogs', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(newPost),
            });

            alert('Blog saved successfully!');
            setTitle('');
            setContent('');
        } catch (error) {
            console.error('Error saving blog:', error);
        }
    };

    return (
        <>
            <div className={styles.addFrom}>
                <form onSubmit={handleSubmit} className={styles.fromLayout}>
                    <div className={styles.formGroup}>
                        <label className={styles.formLabel}>Title:</label>
                        <input className={styles.formInput}
                               type="text"
                               value={formTitle}
                               onChange={(e) => setTitle(e.target.value)}
                               required
                        />
                    </div>
                    <div className={styles.formGroup}>
                        <label className={styles.formLabel}>Write Your Blog Post Content:</label>
                        <textarea
                            className={styles.formTextarea}
                            rows={6}
                            value={formContent}
                            onChange={(e) => setContent(e.target.value)}
                            required
                        />
                    </div>
                    <button className={styles.formSubmit} type="submit">Add Post</button>
                </form>
            </div>
        </>
    );
}